export interface Assignment {
  id: number;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
  due_at: string | null;
  lock_at: string | null;
  unlock_at: string | null;
  has_overrides: boolean;
  course_id: number;
  html_url: string;
  submissions_download_url: string;
  assignment_group_id: number;
  due_date_required: boolean;
  allowed_extensions: string[];
  max_name_length: number;
  turnitin_enabled: boolean;
  vericite_enabled: boolean;
  turnitin_settings: Record<string, any>;
  grade_group_students_individually: boolean;
  external_tool_tag_attributes: Record<string, any>;
  peer_reviews: boolean;
  automatic_peer_reviews: boolean;
  peer_review_count: number;
  peer_reviews_assign_at: string | null;
  intra_group_peer_reviews: boolean;
  group_category_id: number | null;
  needs_grading_count: number;
  needs_grading_count_by_section: Array<{
    section_id: string;
    needs_grading_count: number;
  }>;
  position: number;
  post_to_sis: boolean;
  integration_id: string | null;
  integration_data: Record<string, any>;
  points_possible: number;
  submission_types: string[];
  has_submitted_submissions: boolean;
  grading_type: string;
  grading_standard_id: number | null;
  published: boolean;
  unpublishable: boolean;
  only_visible_to_overrides: boolean;
  locked_for_user: boolean;
  lock_info: Record<string, any>;
  lock_explanation: string;
  quiz_id: number;
  anonymous_submissions: boolean;
  discussion_topic: Record<string, any>;
  freeze_on_copy: boolean;
  frozen: boolean;
  frozen_attributes: string[];
  submission: Record<string, any>;
  use_rubric_for_grading: boolean;
  rubric_settings: Record<string, any>;
  rubric: any[];
  assignment_visibility: number[];
  overrides: any[];
  omit_from_final_grade: boolean;
  moderated_grading: boolean;
  grader_count: number;
  final_grader_id: number | null;
  grader_comments_visible_to_graders: boolean;
  graders_anonymous_to_graders: boolean;
  grader_names_visible_to_final_grader: boolean;
  anonymous_grading: boolean;
  allowed_attempts: number;
  post_manually: boolean;
  score_statistics: Record<string, any>;
  can_submit: boolean;
}

export interface EditAssignmentParams {
  assignment: {
    name?: string;
    position?: number;
    submission_types?: string[];
    allowed_extensions?: string[];
    turnitin_enabled?: boolean;
    vericite_enabled?: boolean;
    turnitin_settings?: Record<string, any>;
    integration_data?: Record<string, any>;
    integration_id?: string;
    peer_reviews?: boolean;
    automatic_peer_reviews?: boolean;
    notify_of_update?: boolean;
    group_category_id?: number;
    grade_group_students_individually?: boolean;
    external_tool_tag_attributes?: Record<string, any>;
    points_possible?: number;
    grading_type?: string;
    due_at?: string;
    lock_at?: string;
    unlock_at?: string;
    description?: string;
    assignment_group_id?: number;
    assignment_overrides?: any[];
    only_visible_to_overrides?: boolean;
    published?: boolean;
    grading_standard_id?: number;
    omit_from_final_grade?: boolean;
    moderated_grading?: boolean;
    grader_count?: number;
    final_grader_id?: number;
    grader_comments_visible_to_graders?: boolean;
    graders_anonymous_to_graders?: boolean;
    grader_names_visible_to_final_grader?: boolean;
    anonymous_instructor_annotations?: boolean;
    anonymous_grading?: boolean;
    allowed_attempts?: number;
    annotatable_attachment_id?: number;
  };
}
